# Generated by Django 3.2.25 on 2024-12-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Cast',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Plot',
            field=models.CharField(max_length=500),
        ),
    ]
