# Generated by Django 3.2.25 on 2024-12-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_auto_20241228_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='YearOfRelease',
            field=models.IntegerField(),
        ),
    ]
