# Generated by Django 3.2.25 on 2024-12-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_alter_movie_yearofrelease'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Favourite',
            field=models.BooleanField(default=False),
        ),
    ]
